# https://hub.docker.com/r/library/node/tags/
image: node:latest# This folder is cached between builds
 
stages:
  - build
  - test
  - deploycache:
  paths:
  - node_modules/build:
  stage: build
  script:
    - npm install
    - npm run-script buildtest:
  stage: test
  script:
    - echo "Running react test suite......"deploy:
  stage: deploy
  script:
    - npm run-script deploy